version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mariadb", "-u", "myuser", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8180:8180"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  db_data:
